<?php


namespace app\Http\Controllers;


use App\Models\Retailer;
use App\Models\User;
use Laravel\Lumen\Testing\TestCase;

class TransactionControllerTest extends TestCase
{
    public function createApplication()
    {
        return require './bootstrap/app.php';
    }

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testUserShouldBeExistingOnProviderToTransfer()
    {
        $this->artisan('passport:install');
        $user = User::factory()->create();
        $payload = [
            'provider' => 'user',
            'payee_id' => '998',
            'amount' => 100
        ];
        $request = $this->actingAs($user, 'users')
            ->post(route('transaction'), $payload);

        $request->assertResponseStatus(422);
    }

    public function testRetailerShouldNotTransfer()
    {
        $this->artisan('passport:install');
        $retailer = Retailer::factory()->create();
        $payload = [
            'provider' => 'user',
            'payee_id' => '999',
            'amount' => 100
        ];
        $request = $this->actingAs($retailer, 'retailer')
            ->post(route('transaction'), $payload);

        $request->assertResponseStatus(422);
    }

    public function testUserShouldHaveMoneyToPerformSomeTransaction()
    {
        $this->artisan('passport:install');
        $payer = User::factory()->create();
        $payee = User::factory()->create();

        $payload = [
            'provider' => 'user',
            'payee_id' => $payee->id,
            'amount' => 100
        ];
        $request = $this->actingAs($payer, 'retailer')
            ->post(route('transaction'), $payload);

        $request->assertResponseStatus(422);
    }

}
